type Client @table {
  firstName: String!
  lastName: String!
  email: String!
  createdAt: Timestamp!
  phoneNumber: String
  address: String
  companyName: String
}

type OnboardingTask @table {
  client: Client
  name: String!
  isCompleted: Boolean!
  createdAt: Timestamp!
  description: String
  completionDate: Timestamp
}

type Document @table {
  client: Client
  filename: String!
  fileUrl: String!
  uploadDate: Timestamp!
  documentType: String!
  description: String
}

type SupportMessage @table {
  client: Client
  messageContent: String!
  sentAt: Timestamp!
  isFromClient: Boolean!
  replyToMessageId: UUID
}

type Room @table {
  name: String!
  capacity: Int!
  createdAt: Timestamp!
  description: String
  amenities: [String]
}

type Booking @table {
  client: Client
  room: Room
  startTime: Timestamp!
  endTime: Timestamp!
  bookingDate: Date!
  createdAt: Timestamp!
  purpose: String
}